package:
  name: boost
  version: "1.55.0"

source:
  fn: boost_1_55_0.zip
  url: http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.zip/download
  sha1: 1d479557177c49d74001c904979b60cce8cc2d12

build:
  number: 1

requirements:
  build:
    - python
    - bzip2 1.0.6
    - zlib 1.2.7  # [win]

  run:
    - python
    - bzip2 1.0.6
    - zlib 1.2.7  # [win]

about:
  home: http://www.boost.org/
  license: Boost Software License
